version: '3.7'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    ports:
      - 8002:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54322:5432"
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
