version: '3.7'
services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=spiski_user
      - POSTGRES_PASSWORD=spiski_dev
      - POSTGRES_DB=spiski_dev

volumes:
  postgres_data:
