version: '3.7'
services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=spiski_user
      - POSTGRES_PASSWORD=spiski_dev
      - POSTGRES_DB=spiski_dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web
  worker:
    build: ./worker
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
