# Generated by Django 3.1 on 2020-10-02 00:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detention",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("time", models.TimeField(null=True)),
                (
                    "time_precision",
                    models.IntegerField(
                        choices=[
                            (0, "1 minute"),
                            (1, "5 minutes"),
                            (2, "10 minutes"),
                            (3, "30 minutes"),
                            (4, "1 hour"),
                            (5, "2 hours"),
                            (6, "3 hours"),
                        ]
                    ),
                ),
                ("details", models.TextField(default="")),
                ("location", models.TextField(default="")),
                ("punishment", models.IntegerField()),
                ("court", models.TextField(default="")),
                ("judge", models.TextField(default="")),
                (
                    "articles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(max_length=10), size=None
                    ),
                ),
                ("freed_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Inmate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("patronymic", models.TextField(null=True)),
                ("birth_date", models.DateField()),
                ("metadata", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(null=True)),
                ("text", models.TextField()),
                ("origin", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Prison",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(default="")),
                ("last_name", models.TextField(default="")),
                ("patronymic", models.TextField(default="")),
                ("birth_date", models.DateField(null=True)),
                ("match_confidence", models.FloatField(null=True)),
                (
                    "inmate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cage.inmate",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cage.list"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="list",
            name="prison",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cage.prison",
            ),
        ),
        migrations.CreateModel(
            name="Imprisonment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cells",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                ("date", models.DateTimeField(null=True)),
                (
                    "detention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cage.detention"
                    ),
                ),
                (
                    "prison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cage.prison"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detention",
            name="inmate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cage.inmate"
            ),
        ),
    ]
