# Generated by Django 3.1 on 2020-10-11 19:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detention",
            name="freed_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="detention",
            name="time_precision",
            field=models.IntegerField(
                choices=[
                    (0, "1 minute"),
                    (1, "5 minutes"),
                    (2, "10 minutes"),
                    (3, "30 minutes"),
                    (4, "1 hour"),
                    (5, "2 hours"),
                    (6, "3 hours"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="imprisonment",
            name="cells",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cage.list",
            ),
        ),
    ]
