# Generated by Django 3.1 on 2020-11-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cage", "0004_list_date_type_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmate",
            name="patronymic",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
