name: publish

on:
  release:
    types: [ published ]

jobs:

  publish:

    runs-on: ubuntu-latest

    env:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
      DEPLOY_REPO: ${{ secrets.DEPLOY_REPO }}

    steps:
      - uses: actions/checkout@v2
      - name: Publish app
        run: |

          echo "Login to docker hub"
          docker login --username "$DEPLOY_USERNAME" -p "$DEPLOY_TOKEN"

          # $GITHUB_REF is in the form of 'refs/tags/<tag>'
          DEPLOY_TAG=$(echo "$GITHUB_REF" | awk -F "/" '{print($3)}')
          IMAGE_TAG=$DEPLOY_USERNAME/$DEPLOY_REPO:app-$DEPLOY_TAG

          cd app/
          echo "Building $IMAGE_TAG"
          docker build . -t $IMAGE_TAG -f Dockerfile.prod

          echo "Pushing to the docker hub"
          docker push $IMAGE_TAG

          echo "The image was successfully pushed"
      - name: Publish nginx
        run: |

          echo "Login to docker hub"
          docker login --username "$DEPLOY_USERNAME" -p "$DEPLOY_TOKEN"

          # $GITHUB_REF is in the form of 'refs/tags/<tag>'
          DEPLOY_TAG=$(echo "$GITHUB_REF" | awk -F "/" '{print($3)}')
          IMAGE_TAG=$DEPLOY_USERNAME/$DEPLOY_REPO:nginx-$DEPLOY_TAG

          cd nginx/
          echo "Building $IMAGE_TAG"
          docker build . -t $IMAGE_TAG

          echo "Pushing to the docker hub"
          docker push $IMAGE_TAG

          echo "The image was successfully pushed"
